### ISSUE TITLE
Great Code; Helpful Dev

### ISSUE THREAD

**Issue by geomlattice** [coinchimp/kaspa-krc20-apps#6]
![image](https://github.com/user-attachments/assets/afd9333b-90cd-40e5-bb3d-dd14016cb0ac)

I'm not sure if what you have here in the script builder is correct, but I don't know exactly how it should be fixed. In a go script, I've seen the data between kasplex and json listed before as a byte of 0x01, then a byte of 0x00, then 0x00 and then json data. "kasplex" was also made byte, while the jsonData appears to not have been. Does this Buffer.from call work with bytes perhaps?

I have gotten txs to go through and the blocks are verified but I see nothing on the Kasplex testnet 10 indexer for my submissions. I'm thinking somehow kasplex isn't seeing what this source code offers for deploy.ts and mint.ts in the top directory. I am not sure what is going on.

**Comment by coinchimp** [comment]
Hi,

It's working for me. Just did 5K mints on testnet with 10 independent processes running in containers.
No problems so far.
Just don't try run those with the same privateKey/Addresses. Or the node might reject them thinking there's a duplicated UTXO with unspent one still in the mempool. I added a time out of 5 min, in case the UTXO change doesn't come up, if you have issues after that, trying raising the priority fees.

Other issue could be: if you manipulate the script at the data part. ensure all the variables are string outputs, or force them with `toString()`

```ts 
const data = { "p": "krc-20", "op": "mint", "tick": ticker };
```
If you have for example an number instead, the process will pass and spent, but you don't get it processed from kasplex indexer, and they won't give you even a notification via the op list at the API for your address.

You info looks the same to me. Just ensure to be using TS. I use `bun` to make it simpler.
```ts
const script = new ScriptBuilder()
  .addData(publicKey.toXOnlyPublicKey().toString())
  .addOp(Opcodes.OpCheckSig)
  .addOp(Opcodes.OpFalse)
  .addOp(Opcodes.OpIf)
  .addData(Buffer.from("kasplex"))
  .addI64(0n)
  .addData(Buffer.from(JSON.stringify(data, null, 0)))
  .addOp(Opcodes.OpEndIf);
  ```
It's aligned with what Kasplex asked: https://docs.kasplex.org/protocols/data-insertion-mechanism  
I got the `Buffer.from` from a KaffinPX example on Discord. It wasn't working for me until I added that. You can get more details on `development` channel at Kaspa Discord. They are very responsive.
  
  CC

**Comment by geomlattice** [comment]
Awesome thanks for the feedback! 

I am trying to deploy on testnet and also transfer, but so far I can only get mint operations to go through. I raise the gas fee to be above 1000 whenever I deploy, and yet still the kasplex indexer isn't picking up on the revealed script.

**Comment by geomlattice** [comment]
Actually I noticed your transfer script works! 

Great work. I am just working through my confusion here

**Comment by coinchimp** [comment]
> Awesome thanks for the feedback!
> 
> I am trying to deploy on testnet and also transfer, but so far I can only get mint operations to go through. I raise the gas fee to be above 1000 whenever I deploy, and yet still the kasplex indexer isn't picking up on the revealed script.
Did you try https://github.com/coinchimp/kaspa-krc20-apps/blob/main/deploy.ts for the deploy?  I raised the priorityfee sometimes  to make it go thru

**Comment by geomlattice** [comment]
Hi it's mainnet day!

So I am trying to run mint with local node connection; I changed the websocket port from 17210 to 17110. I am connected to the RPC, no URLs are detected as logged, and then I get an insufficient funds error. I have around 200 kas in the address that I am working with and my gas is only set to 1. I get insufficient funds error even with 0 priority fee. 

I am not sure what is going on here; could you please help troubleshoot a bit?

**Comment by coinchimp** [comment]
Priority fees are crazy high. I could make a few, one by one and with patience and using higher fees. This is a manual and basic app. Not much you can do when the network is overloaded like it is now.

**Comment by coinchimp** [comment]
closing it after 3 days
